extends Node

signal game_state_changed(old_state: int, new_state: int)
signal stage_started(stage_index: int)
signal stage_cleared(stage_index: int)
signal stage_transition_started(from_stage: int, to_stage: int)
signal stage_transition_completed(stage_index: int)
signal player_damaged(amount: int, remaining_hp: int)
signal player_healed(amount: int, remaining_hp: int)
signal monster_killed(monster: Node)
signal exp_changed(level: int, exp: int, exp_to_next: int)
signal upgrade_selected(upgrade_id: String)
signal combo_changed(combo: int)
signal gold_changed(total_gold: int)
signal wood_changed(total_wood: int)
signal stage_countdown_changed(remaining_sec: float)
signal tower_height_changed(height_m: float, target_m: float)
signal equipment_changed
signal forge_buff_applied(buff_name_cn: String, delta_pct: float, world_pos: Vector2)
signal forge_session_complete(rarity: String, stacked_count: int)
